Repository microsoft/MInference, pull requests merged in 2024-07, with the labels that each got.

#3 Doc(MInference): update paper information
  .github/workflows/release.yml
  .github/workflows/scripts/build.sh
  README.md
Labels: documentation, feature

#4 Feature(MInference): fix unittest
  .github/workflows/unittest.yml
Labels: feature

#6 Hotfix(MInference): fix the pip setup issue
  .github/workflows/release.yml
  .github/workflows/scripts/build.sh
  .github/workflows/unittest.yml
  .gitignore
  README.md
  minference/configs/__init__.py
  minference/modules/__init__.py
  minference/ops/__init__.py
  minference/version.py
  setup.py
Labels: bug, documentation

#8 Hotfix(MInference): fix the pip setup
  .github/workflows/release.yml
  .github/workflows/scripts/build.sh
  .github/workflows/scripts/pytorch-install.sh
  MANIFEST.in
  README.md
  minference/version.py
  setup.py
Labels: bug, documentation

#9 Hotfix(MInference): fix the yaml
  .github/workflows/release.yml
Labels: bug

#10 Hotfix(Minference): fix the yaml
  .github/workflows/release.yml
Labels: bug

#11 Feature(MInference): add bdist cache
  .github/workflows/release.yml
  minference/version.py
  setup.py
Labels: feature

#14 Hotfix(MInference): fix the configs in pip
  MANIFEST.in
  README.md
  minference/modules/minference_forward.py
Labels: bug, documentation

#15 Prerelease(MInference): update version
  minference/version.py
Labels: documentation

#19 add vllm support for 0.4.2 and 0.4.3
  README.md
  Transparency_FAQ.md
  minference/modules/minference_forward.py
  minference/patch.py
  minference/version.py
Labels: bug, documentation

#22 Feature(MInference): update HF demo information, thanks @AK's sponsoring
  README.md
Labels: documentation

#30 Hotfix(MInference): fix the import warnings, fix the apply_rotary_pos…
  README.md
  experiments/README.md
  minference/modules/minference_forward.py
  minference/ops/block_sparse_flash_attention.py
  minference/ops/pit_sparse_flash_attention_v2.py
  minference/patch.py
  setup.py
Labels: bug, documentation, feature

#31 Feature(MInference): add unittest
  Makefile
  experiments/benchmarks/benchmark_e2e.py
  tests/test_e2e.py
Labels: feature

#32 Prerelease(MInference): for 0.1.4.post2
  minference/version.py
Labels: feature

#35 Feature(MInference): add triton-based decoding in case flash_attn is not available
  README.md
  minference/modules/inf_llm.py
  minference/modules/minference_forward.py
  minference/ops/block_sparse_flash_attention.py
  minference/ops/flash_attn_triton.py
  minference/version.py
  setup.py
Labels: feature

#44 Hotfix(MInference): fix vllm>=0.4.1
  README.md
  minference/modules/minference_forward.py
  minference/patch.py
  minference/version.py
Labels: bug

#54 Feature(MInference): support llama 3.1
  README.md
  minference/configs/Llama_3.1_8B_Instruct_128k_kv_out_v32_fit_o_best_pattern.json
  minference/configs/model2path.py
  minference/modules/minference_forward.py
  minference/version.py
Labels: documentation, feature
