Repository microsoft/MInference, pull requests merged in 2024-12, with the labels that each got.

#97 Feature(SCBench): update scbench information
  README.md
  images/SCBench_onepage.png
  scbench/readme.md
Labels: documentation

#100 Feature(FlexPrefill): add flex-prefill
  README.md
  experiments/benchmarks/benchmark_e2e.py
  experiments/benchmarks/benchmark_e2e_vllm.py
  experiments/benchmarks/benchmark_e2e_vllm_tp.py
  experiments/infinite_bench/args.py
  experiments/infinite_bench/run_infinitebench.py
  experiments/needle_in_a_haystack/needle_test.py
  experiments/needle_in_a_haystack/needle_tools.py
  experiments/ppl/run_ppl.py
  experiments/ruler/pred/call_api.py
  minference/minference_configuration.py
  minference/models_patch.py
  minference/modules/flexprefill.py
  minference/modules/forward.py
  minference/modules/minference_forward.py
  scbench/args.py
  scbench/run_scbench.py
Labels: documentation, feature

#101 Fix(SCBench): fix the pipeline and load dataset
  README.md
  scbench/compute_scores.py
  scbench/readme.md
  scbench/run_scbench.py
Labels: bug, documentation

#104 Fix(SCBench): fix default seq length
  README.md
  scbench/args.py
  scbench/scripts/run_all_tasks.sh
Labels: bug, documentation

#105 Feature(SCBench): update scbench scripts
  README.md
  minference/version.py
  scbench/readme.md
  scbench/scripts/run_all_tasks.sh
  scbench/scripts/run_single_method.sh
Labels: documentation, feature

#106 Fix(SCBench): bug fix when `use_cache == False`
  minference/modules/forward.py
  minference/patch.py
Labels: bug
